### ISSUE TITLE
Ajouter un message au permanence

### ISSUE THREAD

**Issue by ArnaudBan** [Recyclindre/manage-permanences#22]
On va avoir besoin de pouvoir ajouter un message informatif sur certaine permanence du type : 

* Cette permanence sera un retournement, venez nombreux !
* On profite de cette permanence pour faire un apéro sérieux

Il faudrait prévoir un design particulier pour ca ( ping @baptistegimonnet  )

**Comment by baptistegimonnet** [comment]
@ArnaudBan  : voici une proposition.
Border + background : #769ff6
Ajout d'un libellé "RETOURNEMENT" ou "APERO"  : font-style:14px;color:#769ff6;text-transform:uppercase

on peut également ajouter un title au rollover, comme tu as fait sur le bouton de connexion avec les textes "Cette permanence sera un retournement, venez nombreux !" 

Côté admin, ajout d'un champ evenement sur la permanence avec liste des choix ? 

![image](https://user-images.githubusercontent.com/14927929/48335447-03363a80-e65e-11e8-8968-7ccf121c2c25.png)
